apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "9"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"envoy","namespace":"envoy-redis"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"envoy"}},"template":{"metadata":{"labels":{"app":"envoy"}},"spec":{"containers":[{"args":["-c","/etc/envoy/envoy.yaml","-l","info"],"image":"envoyproxy/envoy:v1.34-latest","imagePullPolicy":"IfNotPresent","livenessProbe":{"httpGet":{"path":"/ready","port":9901},"initialDelaySeconds":30,"periodSeconds":10},"name":"envoy","ports":[{"containerPort":6379},{"containerPort":9901}],"readinessProbe":{"httpGet":{"path":"/ready","port":9901},"initialDelaySeconds":5,"periodSeconds":5},"resources":{"limits":{"cpu":"2000m","memory":"2Gi"},"requests":{"cpu":"200m","memory":"256Mi"}},"volumeMounts":[{"mountPath":"/etc/envoy/envoy.yaml","name":"envoy-config-volume","subPath":"envoy.yaml"}]}],"volumes":[{"configMap":{"name":"envoy-config"},"name":"envoy-config-volume"}]}}}}
  creationTimestamp: "2025-07-11T11:21:12Z"
  generation: 10
  name: envoy
  namespace: envoy-redis
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: envoy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2025-07-24T16:46:10Z"
      labels:
        app: envoy
    spec:
      containers:
      - args:
        - -c
        - /etc/envoy/envoy.yaml
        - -l
        - info
        image: amaan75/envoy-proxy:v1.34.7
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: 9901
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: envoy
        ports:
        - containerPort: 6379
          protocol: TCP
        - containerPort: 9901
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: 9901
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/envoy/envoy.yaml
          name: envoy-config-volume
          subPath: envoy.yaml
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: envoy-config
        name: envoy-config-volume

